tab-format: "{prefix}{prefixSplit}{username}{suffixSplit}{suffix}"
chat-format: "{prefix}{prefixSplit}{username}{suffixSplit}{suffix} » {message}"
prefix-split-character: " "
suffix-split-character: " "